"""Readiness report export — renders a ReadinessResult as a markdown report.

Follows the template structure from the architecture doc (Section 14).
"""

from services.readiness import ReadinessResult


def generate_report_markdown(
    result: ReadinessResult,
    practice_name: str,
) -> str:
    """Render the readiness report as a formatted markdown document."""
    lines: list[str] = []

    # Header
    lines.append("# LaunchLab Readiness Report")
    lines.append(f"## {practice_name} — Agent Deployment Assessment")
    lines.append("")
    lines.append(
        f"**Generated:** {result.eval_run_date.strftime('%Y-%m-%d %H:%M UTC')}"
    )
    lines.append(f"**Eval Run:** {result.eval_run_id}")
    lines.append(f"**Eval Suite:** v1 ({result.scenario_count} scenarios)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Overall readiness
    lines.append(
        f"## Overall Readiness: {result.overall_score}/100 "
        f"— {result.readiness_label}"
    )
    lines.append("")

    # Category scores table
    lines.append("## Category Scores")
    lines.append("")
    lines.append("| Category | Pass Rate | Avg Score | Cases | Status |")
    lines.append("|----------|-----------|-----------|-------|--------|")

    status_icons = {"pass": "Pass", "warn": "Needs Attention", "fail": "Fail"}
    for cs in result.category_scores:
        icon = status_icons.get(cs.status, cs.status)
        lines.append(
            f"| {cs.category.replace('_', ' ').title()} "
            f"| {cs.pass_rate:.0%} "
            f"| {cs.avg_score:.0%} "
            f"| {cs.case_count} "
            f"| {icon} |"
        )

    lines.append("")

    # Scenario results summary
    lines.append("## Scenario Results")
    lines.append("")
    lines.append(
        f"**{result.pass_count}/{result.scenario_count} scenarios passed** "
        f"({result.pass_count / result.scenario_count:.0%} pass rate)"
        if result.scenario_count
        else "No scenarios evaluated."
    )
    lines.append("")

    # Failure themes
    if result.failure_themes:
        lines.append("## Top Failure Themes")
        lines.append("")
        for i, theme in enumerate(result.failure_themes, 1):
            lines.append(f"{i}. **[{theme.severity.upper()}]** {theme.theme}")
            lines.append(
                f"   - Affected scenarios: {', '.join(theme.affected_scenarios)}"
            )
        lines.append("")

    # Recommendation
    lines.append("## Recommendation")
    lines.append("")
    lines.append(result.recommendation)
    lines.append("")

    # Constraints
    if result.constraints:
        lines.append("## Deployment Constraints")
        lines.append("")
        for constraint in result.constraints:
            lines.append(f"- {constraint}")
        lines.append("")

    # Next steps
    lines.append("## Next Steps")
    lines.append("")
    if result.readiness_level == "ready_for_pilot":
        lines.append("1. Begin supervised pilot deployment")
        lines.append("2. Monitor conversation quality in production")
        lines.append("3. Re-run eval suite periodically to catch regressions")
    elif result.readiness_level == "ready_for_limited_pilot":
        lines.append("1. Deploy to limited pilot with restrictions noted above")
        lines.append("2. Address failure themes to expand pilot scope")
        lines.append("3. Re-run eval suite after changes")
    else:
        lines.append("1. Review and address the failure themes listed above")
        lines.append("2. Update agent configuration or guardrails as needed")
        lines.append("3. Re-run the eval suite to measure improvement")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by LaunchLab — Healthcare Agent Launch Simulator*")

    return "\n".join(lines)
